<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ClaimRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $id = $this->claim ? $this->claim->id : null;
        return [
            //'claim_no' => 'required|string|max:20|unique:claims,claim_no'.($id?",$id,id":""), // autogenerated
            'n_PolicyNoId_FK' => 'required'
        ];
    }
}
